name: Shell TestScript

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  testscript:
    runs-on: ubuntu-latest

    steps:
      - name: Check out target branch
        if: github.event_name == 'push'
        uses: actions/checkout@v4

      - name: Check out target branch
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run testscript
        run: |
          find ./ -name "*.lst" -type f -exec sh -c 'python shell.py $(basename $0)' {} \;
